---
- name: Converge
  hosts: all
  tasks:
    # required, as we skip the real install of docker
    - name: ensure group docker exists
      group:
        name: docker
        system: true
    - name: "Include rls.gns3server"
      include_role:
        name: "rls.gns3server"
  post_tasks:
    - name: "Test gns3 uri works"
      uri:
        url: "http://{{ ansible_default_ipv4.address }}:3080/static/web-ui/bundled"
      register: _urires
      retries: 3
      delay: 10
      until: "_urires.status == 200"
