# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2 smartindent nu
---
name: molecule test
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: 'rls.gns3server'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install test dependencies.
        run: pip3 install ansible "molecule[docker,lint]" yamllint ansible-lint requests

      - name: debug env
        run: env

      - name: run molecule tests
        run: molecule test
        working-directory: rls.gns3server
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
